select * from Worker


create database KPI_TARGET
CREATE TABLE KPI_CHANNEL_DIM
(
DATE_CREATED	    DATE,
IS_RECORD_INACTIVE	CHAR,
LAST_MODIFIED_DATE	DATE,
LIST_ID	            INT,
LIST_ITEM_NAME	    VARCHAR(20),
KPI_DW_SKEY	        INT Primary key,
KPI_DW_INSERT_DATE	DATE,
KPI_DW_UPDATE_DATE	DATE
)

drop table KPI_CHANNEL_DIM

CREATE TABLE KPI_LOCATION_DIM
(
LOCATION_ID	        INT,
ADDRESS             VARCHAR(100),
CITY	            VARCHAR(50),
COUNTRY	            VARCHAR(50),
DATE_LAST_MODIFIED	DATE,
FULL_NAME	        VARCHAR(50),
ISINACTIVE	        VARCHAR(5),
NAME	            VARCHAR(50),
KPI_DW_SKEY	        INT  Primary key,
KPI_DW_INSERT_DATE	DATE,
KPI_DW_UPDATE_DATE	DATE
)

CREATE TABLE KPI_DEPARTMENT_DIM
(
DATE_LAST_MODIFIED	 DATE,
DEPARTMENT_ID	     INT,
ISINACTIVE	         VARCHAR(5),
NAME	             VARCHAR(10),
WS_DESCRIPTION	     VARCHAR(50),
KPI_DW_SKEY	         INT PRIMARY KEY,
KPI_DW_INSERT_DATE	 DATE,
KPI_DW_UPDATE_DATE	 DATE
)

CREATE TABLE KPI_TRANSACTION_LINE_FACT
(
TRANSACTION_ID	    INT,
TRANSACTION_LINE_ID	INT,
TRANID	            VARCHAR(30),
TRANSACTION_TYPE	VARCHAR(50),
TRANDATE	        DATE,
KPI_CHANNEL_SKEY	INT,
KPI_LOCATION_SKEY	INT,
KPI_DEPARTMENT_SKEY	INT,
KPI_ITEM_SKEY	    INT,
AMOUNT	            INT,
COST	            INT,
UNITS	            INT,
KPI_DW_SKEY	        INT PRIMARY KEY
)

CREATE TABLE KPI_ITEM_DIM
(
ITEM_ID	                        INT,
SKU	                            VARCHAR(100),
TYPE_NAME	                    VARCHAR(30),
SALESDESCRIPTION	            VARCHAR(100),
KPI_DW_SKEY	                    INT  PRIMARY KEY,
KPI_DW_INSERT_DATE	            DATE,
KPI_DW_UPDATE_DATE	            DATE,
KPI_CLASS_SKEY	                INT,
WS_MERCHANDISE_DEPARTMENT_SKEY	INT,
WS_MERCHANDISE_COLLECTION_SKEY	INT,
WS_MERCHANDISE_CLASS_SKEY	    INT,
WS_MERCHANDISE_SUBCLASS_SKEY	INT
)

CREATE TABLE KPI_CLASS_DIM
(
CLASS_ID	         INT,
DATE_LAST_MODIFIED	 DATE,
FULL_NAME	         VARCHAR(30),
ISINACTIVE	         VARCHAR(5),
NAME	             VARCHAR(5),
KPI_DW_SKEY	         INT PRIMARY KEY,
KPI_DW_INSERT_DATE	 DATE,
KPI_DW_UPDATE_DATE	 DATE
)

CREATE TABLE KPI_ITEM_MERCHANDISE_DEPTARMENT_DIM
(
ITEM_MERCHANDISE_DEPARTMENT_ID	INT,
DESCRIPTION	                    VARCHAR(50),
ITEM_MERCHANDISE_DEPARTMENT_NA	VARCHAR(10),
KPI_DW_SKEY	                    INT PRIMARY KEY,
KPI_DW_INSERT_DATE	            DATE,
KPI_DW_UPDATE_DATE	            DATE
)

CREATE TABLE KPI_ITEM_MERCHANDISE_COLLECTION_DIM
(
ITEM_MERCHANDISE_COLLECTION_ID	INT,
DESCRIPTION	                    VARCHAR(50),
ITEM_MERCHANDISE_COLLECTION_NA	VARCHAR(50),
KPI_DW_SKEY	                    INT,
KPI_DW_INSERT_DATE	            DATE,
KPI_DW_UPDATE_DATE	            DATE
)

CREATE TABLE KPI_ITEM_MERCHANDISE_CLASS_DIM	
(
ITEM_MERCHANDISE_CLASS_ID	INT,
DESCRIPTION	                VARCHAR(50),
ITEM_MERCHANDISE_CLASS_NAME	VARCHAR(50),
KPI_DW_SKEY	                INT PRIMARY KEY,
KPI_DW_INSERT_DATE	        DATE,
KPI_DW_UPDATE_DATE	        DATE
)

CREATE TABLE KPI_TEM_MERCHANDISE_SUBCLASS_DIM
(
ITEM_MERCHANDISE_SUBCLASS_ID	INT,
DESCRIPTION	                    VARCHAR(50),
ITEM_MERCHANDISE_SUBCLASS_NAME	VARCHAR(10),
KPI_DW_SKEY	                    INT PRIMARY KEY,
KPI_DW_INSERT_DATE	            DATE,
KPI_DW_UPDATE_DATE	            DATE
)

ALTER TABLE KPI_TRANSACTION_LINE_FACT ADD CONSTRAINT FK_KPI_TRANSACTION_LINE_FACT_KPI_CHANNEL_SKEY
FOREIGN KEY(KPI_CHANNEL_SKEY) REFERENCES KPI_CHANNEL_DIM(KPI_DW_SKEY)

ALTER TABLE KPI_TRANSACTION_LINE_FACT ADD CONSTRAINT FK_KPI_TRANSACTION_LINE_FACT_KPI_LOCATION_SKEY
FOREIGN KEY(KPI_LOCATION_SKEY) REFERENCES KPI_LOCATION_DIM(KPI_DW_SKEY)

ALTER TABLE KPI_TRANSACTION_LINE_FACT ADD CONSTRAINT FK_KPI_TRANSACTION_LINE_FACT_KPI_DEPARTMENT_SKEY
FOREIGN KEY(KPI_DEPARTMENT_SKEY) REFERENCES KPI_DEPARTMENT_DIM(KPI_DW_SKEY)

ALTER TABLE KPI_TRANSACTION_LINE_FACT ADD CONSTRAINT FK_KPI_TRANSACTION_LINE_FACT_KPI_ITEM_SKEY
FOREIGN KEY(KPI_ITEM_SKEY) REFERENCES KPI_ITEM_DIM(KPI_DW_SKEY)

ALTER TABLE KPI_ITEM_DIM ADD CONSTRAINT FK_KPI_ITEM_DIM_KPI_CLASS_SKEY
FOREIGN KEY(KPI_CLASS_SKEY) REFERENCES KPI_CLASS_DIM(KPI_DW_SKEY)

ALTER TABLE KPI_ITEM_DIM ADD CONSTRAINT FK_KPI_ITEM_DIM_WS_MERCHANDISE_DEPARTMENT_SKEY
FOREIGN KEY(WS_MERCHANDISE_DEPARTMENT_SKEY) REFERENCES KPI_ITEM_MERCHANDISE_DEPTARMENT_DIM(KPI_DW_SKEY)


ALTER TABLE KPI_ITEM_DIM ADD CONSTRAINT FK_KPI_ITEM_DIM_WS_MERCHANDISE_COLLECTION_SKEY
FOREIGN KEY(WS_MERCHANDISE_COLLECTION_SKEY) REFERENCES KPI_ITEM_MERCHANDISE_COLLECTION_DIM(KPI_DW_SKEY)

ALTER TABLE KPI_ITEM_DIM ADD CONSTRAINT FK_KPI_ITEM_DIM_WS_MERCHANDISE_CLASS_SKEY
FOREIGN KEY(WS_MERCHANDISE_CLASS_SKEY) REFERENCES KPI_ITEM_MERCHANDISE_CLASS_DIM(KPI_DW_SKEY)

ALTER TABLE KPI_ITEM_DIM ADD CONSTRAINT FK_KPI_ITEM_DIM_WS_MERCHANDISE_SUBCLASS_SKEY
FOREIGN KEY(WS_MERCHANDISE_SUBCLASS_SKEY) REFERENCES KPI_TEM_MERCHANDISE_SUBCLASS_DIM(KPI_DW_SKEY)
